# Generated by Django 5.0.2 on 2024-02-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('practice', models.CharField(max_length=50)),
                ('doctor_url', models.URLField()),
                ('years_of_experience', models.SmallIntegerField(blank=True)),
            ],
        ),
    ]
