# Generated by Django 4.0.6 on 2024-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
