# Generated by Django 4.0.6 on 2024-03-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0002_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_img_url',
            field=models.URLField(null=True),
        ),
    ]
