# Generated by Django 4.0.6 on 2024-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0003_doctor_doctor_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
