# Generated by Django 4.0.6 on 2024-05-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0005_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_img_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', null=True),
        ),
    ]
