# Generated by Django 4.0.6 on 2024-05-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0006_alter_doctor_doctor_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
