# Generated by Django 4.0.6 on 2024-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistapp', '0007_rename_f_name_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
